# Generated by Django 5.2.5 on 2025-08-28 06:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود العميل"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم العميل")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="العنوان"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود الصنف"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الصنف")),
                ("uom", models.CharField(max_length=50, verbose_name="وحدة القياس")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="حد المخزون الأدنى",
                    ),
                ),
            ],
            options={
                "verbose_name": "صنف مخزن",
                "verbose_name_plural": "أصناف المخزن",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود الشريك"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الشريك")),
                (
                    "share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة الحصة (٪)",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="الرصيد الافتتاحي",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "شريك",
                "verbose_name_plural": "الشركاء",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartnersGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="اسم المجموعة"
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة شركاء",
                "verbose_name_plural": "مجموعات الشركاء",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود المشروع"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المشروع")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("build", "بناء"),
                            ("maintenance", "صيانة"),
                            ("renovation", "ترميم"),
                        ],
                        max_length=20,
                        verbose_name="نوع المشروع",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "قيد التنفيذ"),
                            ("done", "منتهي"),
                            ("hold", "متوقف"),
                        ],
                        default="ongoing",
                        max_length=20,
                        verbose_name="حالة المشروع",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الميزانية التقديرية",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشروع",
                "verbose_name_plural": "المشاريع",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المورد")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "الموردون",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم العقد"
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="قيمة الوحدة في العقد",
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الدفعة المقدمة"
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد الأقساط",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                            ("yearly", "سنوي"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="نوع جدولة الأقساط",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ بداية الأقساط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="accounting.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "partners_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.partnersgroup",
                        verbose_name="مجموعة الشركاء (اختياري)",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقد",
                "verbose_name_plural": "العقود",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_no", models.PositiveIntegerField(verbose_name="رقم القسط")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="قيمة القسط"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=15,
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("PAID", "مدفوع"),
                            ("LATE", "متأخر"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="حالة القسط",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="accounting.contract",
                        verbose_name="العقد",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسط",
                "verbose_name_plural": "الأقساط",
                "ordering": ["contract", "seq_no"],
                "unique_together": {("contract", "seq_no")},
            },
        ),
        migrations.CreateModel(
            name="Safe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="اسم الخزنة/المحفظة"),
                ),
                (
                    "is_partner_wallet",
                    models.BooleanField(
                        default=False, verbose_name="هل هي محفظة شريك؟"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.partner",
                        verbose_name="الشريك (إذا كانت محفظة)",
                    ),
                ),
            ],
            options={
                "verbose_name": "خزنة/محفظة",
                "verbose_name_plural": "الخزائن والمحافظ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ السند"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="المبلغ",
                    ),
                ),
                ("description", models.TextField(verbose_name="البيان/الوصف")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.contract",
                        verbose_name="العقد",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="accounting.installment",
                        verbose_name="القسط",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.partner",
                        verbose_name="الشريك",
                    ),
                ),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.safe",
                        verbose_name="الخزنة/المحفظة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سند قبض",
                "verbose_name_plural": "سندات القبض",
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_from", models.DateField(verbose_name="من تاريخ")),
                ("period_to", models.DateField(verbose_name="إلى تاريخ")),
                (
                    "pre_balances",
                    models.JSONField(default=dict, verbose_name="الأرصدة قبل التسوية"),
                ),
                (
                    "post_balances",
                    models.JSONField(default=dict, verbose_name="الأرصدة بعد التسوية"),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="تحتوي على التحويلات المطلوبة بين الشركاء لتسوية الحسابات.",
                        verbose_name="تفاصيل التسوية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.project",
                        verbose_name="المشروع المرتبط (اختياري)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسوية شركاء",
                "verbose_name_plural": "تسويات الشركاء",
                "ordering": ["-period_to"],
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "إدخال (توريد)"), ("OUT", "إخراج (صرف)")],
                        max_length=3,
                        verbose_name="اتجاه الحركة",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الحركة"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="ملاحظات"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_moves",
                        to="accounting.item",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_moves",
                        to="accounting.project",
                        verbose_name="المشروع (في حالة الصرف)",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة مخزن",
                "verbose_name_plural": "حركات المخزن",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ السند"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="المبلغ",
                    ),
                ),
                ("description", models.TextField(verbose_name="البيان/الوصف")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "expense_head",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="بند المصروف"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.safe",
                        verbose_name="الخزنة/المحفظة",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "سند صرف",
                "verbose_name_plural": "سندات الصرف",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.supplier",
                verbose_name="المورد الافتراضي",
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود الوحدة"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="اسم/وصف الوحدة"),
                ),
                (
                    "building_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم المبنى/العمارة"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("residential", "سكني"),
                            ("commercial", "تجاري"),
                            ("school", "مدرسة"),
                            ("other", "أخرى"),
                        ],
                        default="residential",
                        max_length=20,
                        verbose_name="نوع الوحدة",
                    ),
                ),
                (
                    "price_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="السعر الإجمالي للوحدة",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("res", "سكني"), ("com", "تجاري")],
                        max_length=10,
                        verbose_name="تصنيف الوحدة",
                    ),
                ),
                (
                    "partners_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.partnersgroup",
                        verbose_name="مجموعة الشركاء المالكة",
                    ),
                ),
            ],
            options={
                "verbose_name": "وحدة",
                "verbose_name_plural": "الوحدات",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="unit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract",
                to="accounting.unit",
                verbose_name="الوحدة",
            ),
        ),
        migrations.CreateModel(
            name="PartnersGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="النسبة في المجموعة (٪)",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounting.partnersgroup",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_memberships",
                        to="accounting.partner",
                        verbose_name="الشريك",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو مجموعة",
                "verbose_name_plural": "أعضاء المجموعات",
                "ordering": ["group", "-percent"],
                "unique_together": {("group", "partner")},
            },
        ),
    ]
