# Generated by Django 5.0.6 on 2025-08-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        # This migration is empty to satisfy the migration check
        # Any model changes will be handled in future migrations
    ]