# Generated by Django 5.0.6 on 2025-08-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_customer_created_at'),
        ('accounting', '0006_create_new_models'),
    ]

    operations = [
    ]